### ISSUE TITLE
运行您的run_webcam.py出错

### ISSUE THREAD

**Issue by Coder-TieHH** [Z-Xiong/LightTrack#1]
博主您好，我在运行您的run_webcam.py，总是在这一步出错，能告诉我什么问题吗
![image](https://github.com/Z-Xiong/LightTrack/assets/130418678/5454134b-07b4-4903-9e3c-dd9392fe705e)

**Comment by Z-Xiong** [comment]
--arch LightTrackM_Subnet --resume LightTrackM.pth --video 01.mp4 --stride 16 --path_name back_04502514044521042540+cls_211000022+reg_100000111_ops_32

是这样运行的吗？

**Comment by Coder-TieHH** [comment]
我试试，应该是我运行的命令不对，谢谢您

**Comment by Coder-TieHH** [comment]
ok了，我知道了，运行的命令有问题，谢谢您

**Comment by Coder-TieHH** [comment]
我想问一下，“--path_name back_04502514044521042540+cls_211000022+reg_100000111_ops_32”，--path_name这个参数的作用是什么，这垢面这三个是权重吗，刚接触，请大佬赐教

**Comment by Z-Xiong** [comment]
应该不是权重，这个是网络结构吧。原始的LightTrack是这样给参数的，我就是抄过来的。

**Comment by Coder-TieHH** [comment]
噢噢噢，好的，感觉名字好奇怪，而且在文件里面也没找到

**Comment by Z-Xiong** [comment]
源码里有对这个字符串进行解析的。

**Comment by Coder-TieHH** [comment]
好的，非常感谢您！
