### ISSUE TITLE
看到您在Nanotrack  issues里面提问，想问问您一些问题

### ISSUE THREAD

**Issue by Coder-TieHH** [Z-Xiong/LightTrack#2]
![image](https://github.com/Z-Xiong/LightTrack/assets/130418678/9c0c34a4-3247-4eb6-8277-8d193373a73b)
不知道您在训练的时候遇到过吗

**Comment by Coder-TieHH** [comment]
我在Nano那边提问了，但是没人回答，希望您这边能帮助我😊

**Comment by Z-Xiong** [comment]
我这边没办法复现你的操作，但是这个问题通过单步调试应该可以解决的。

**Comment by Coder-TieHH** [comment]
我单步调试，最后发现这一步是没有运行的（没有报错），直接返回了
细看之下，我发现mapping是没有数据的，很奇怪
![image](https://github.com/Z-Xiong/LightTrack/assets/130418678/a1573a6c-d1c2-4759-a854-1e17be1a415f)

**Comment by Coder-TieHH** [comment]
噢噢噢，我知道了，因为numpy的版本太新了，没有np.float这个属性，改为float就行了，（但是不知道为什么opencv没有报错提示，导致我一直找不到）谢谢大佬，百忙之中回复我的消息😊
